format_version: v1.0
type: UniqueComponent
attributes: {id: FreeRTOS}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: FREERTOS_CPU_CLOCK_HZ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '48000000'}
  - type: Boolean
    attributes: {id: FREERTOS_DAEMON_TASK_STARTUP_HOOK}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: 'true'}
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: FREERTOS_EXPECTED_IDLE_TIME_BEFORE_SLEEP}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: '5'}
  - type: File
    attributes: {id: FREERTOS_HEAP_1_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: FREERTOS_HEAP_4_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: FREERTOS_IDLE_HOOK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: 'true'}
  - type: Combo
    attributes: {id: FREERTOS_MEMORY_MANAGEMENT_CHOICE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: Heap_4}
      - type: User
        attributes: {value: Heap_4}
  - type: Integer
    attributes: {id: FREERTOS_MINIMAL_STACK_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: '256'}
  - type: Combo
    attributes: {id: FREERTOS_TICKLESS_IDLE_CHOICE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: Tickless_Idle}
  - type: Boolean
    attributes: {id: FREERTOS_TICK_HOOK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: 'true'}
  - type: Integer
    attributes: {id: FREERTOS_TIMER_QUEUE_LENGTH}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '10'}
  - type: Integer
    attributes: {id: FREERTOS_TIMER_TASK_PRIORITY}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '3'}
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: FREERTOS_TIMER_TASK_STACK_DEPTH}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: FreeRTOS, value: '256'}
  - type: Integer
    attributes: {id: FREERTOS_TOTAL_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '46080'}
  - type: Boolean
    attributes: {id: FREERTOS_USE_QUEUE_SETS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: 'true'}
  - type: Boolean
    attributes: {id: FREERTOS_USE_TIMERS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '27', y: '95', id: FreeRTOS}
