format_version: v1.0
type: UniqueComponent
attributes: {id: pic32cx_bz2_devsupport}
children:
- type: Symbols
  children:
  - type: File
    attributes: {id: APP_IDLE_TASK_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: APP_IDLE_TASK_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: File
    attributes: {id: APP_USER_EDITS_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: AUTO_LOAD_PDS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: 'true'}
  - type: Boolean
    attributes: {id: BLESTACK_LOADED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: 'true'}
  - type: Boolean
    attributes: {id: CUSTOM_ANT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: 'false'}
  - type: Integer
    attributes: {id: DEVICE_CHECON_PFMWS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: '1'}
  - type: String
    attributes: {id: FREERTOS_CONFIG_PATH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: config/wbz451_curiosity_board/FreeRTOSConfig.h/}
  - type: String
    attributes: {id: FREERTOS_HOOKS_PATH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: '"config/wbz451_curiosity_board/freertos_hooks.c/"'}
  - type: Boolean
    attributes: {id: PDS_LOADED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: 'true'}
  - type: Boolean
    attributes: {id: SLEEP_SUPPORTED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: 'true'}
  - type: String
    attributes: {id: WSS_ENABLE_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pic32cx_bz2_devsupport, value: WSS_ENABLE_BLE}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: RTC_Module}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: rtc}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: RTC_TMR}
- type: ElementPosition
  attributes: {x: '30', y: '201', id: pic32cx_bz2_devsupport}
