configName: wbz451_curiosity_board
folderName: CI_wbz451_curiosity_board
format_version: v1.0
frameworkPath: ../../../EA3_1/H3
processor: WBZ451
projectName: CI_wbz451_curiosity_board
settings:
  PackageFilter: bsp;core;crypto;csp;dev_packs;wireless;wireless-old
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CX-BZ_DFP\1.0.80\WBZ451\atdf\WBZ451.atdf
